In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
# generate array from text file
data = genfromtxt('Computer-Vision-with-Python/DATA/bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
print(X_test.min())
print(X_test.max())

-13.2869
17.1116


In [15]:
# normalizer
from sklearn.preprocessing import MinMaxScaler

In [16]:
scaler_object = MinMaxScaler()

In [17]:
scaler_object.fit(X_train) # do not fit the test set, only train

MinMaxScaler(copy=True, feature_range=(0, 1))

In [18]:
scaled_X_train =  scaler_object.transform(X_train)

In [19]:
scaled_X_test = scaler_object.transform(X_test)

In [20]:
scaled_X_train.max()

1.0000000000000002

In [21]:
scaled_X_train # values now between 0 and 1

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [25]:
from keras.models import Sequential
from keras.layers import Dense

In [27]:
model = Sequential()

model.add(Dense(4,input_dim=4, activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

In [28]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [32]:
model.fit(scaled_X_train,y_train, epochs=50, verbose=2) # verbose gives information back

Epoch 1/50
 - 0s - loss: 0.2476 - accuracy: 0.9184
Epoch 2/50
 - 0s - loss: 0.2398 - accuracy: 0.9217
Epoch 3/50
 - 0s - loss: 0.2329 - accuracy: 0.9217
Epoch 4/50
 - 0s - loss: 0.2254 - accuracy: 0.9282
Epoch 5/50
 - 0s - loss: 0.2181 - accuracy: 0.9336
Epoch 6/50
 - 0s - loss: 0.2114 - accuracy: 0.9314
Epoch 7/50
 - 0s - loss: 0.2051 - accuracy: 0.9304
Epoch 8/50
 - 0s - loss: 0.1987 - accuracy: 0.9336
Epoch 9/50
 - 0s - loss: 0.1923 - accuracy: 0.9369
Epoch 10/50
 - 0s - loss: 0.1864 - accuracy: 0.9369
Epoch 11/50
 - 0s - loss: 0.1807 - accuracy: 0.9380
Epoch 12/50
 - 0s - loss: 0.1745 - accuracy: 0.9402
Epoch 13/50
 - 0s - loss: 0.1690 - accuracy: 0.9478
Epoch 14/50
 - 0s - loss: 0.1644 - accuracy: 0.9467
Epoch 15/50
 - 0s - loss: 0.1588 - accuracy: 0.9489
Epoch 16/50
 - 0s - loss: 0.1548 - accuracy: 0.9532
Epoch 17/50
 - 0s - loss: 0.1503 - accuracy: 0.9521
Epoch 18/50
 - 0s - loss: 0.1456 - accuracy: 0.9587
Epoch 19/50
 - 0s - loss: 0.1416 - accuracy: 0.9543
Epoch 20/50
 - 0s - l

In [34]:
#model.predict_classes(scaled_X_test)

In [35]:
model.metrics_names

['loss', 'accuracy']

In [36]:
from sklearn.metrics import confusion_matrix, classification_report

In [37]:
predictions = model.predict_classes(scaled_X_test)
confusion_matrix(y_test, predictions)

array([[251,   6],
       [  3, 193]])

In [38]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.99      0.98      0.98       257
         1.0       0.97      0.98      0.98       196

    accuracy                           0.98       453
   macro avg       0.98      0.98      0.98       453
weighted avg       0.98      0.98      0.98       453



In [39]:
# save the model
model.save('mymodel.h5')

In [41]:
from keras.models import load_model

newmodel = load_model('mymodel.h5')

In [43]:
#newmodel.predict_classes(scaled_X_test)